### ISSUE TITLE
table width in css

### ISSUE THREAD

**Issue by SepidehAlassi** [dasch-swiss/beol#53] opened 2018-10-26 13:00 UTC
The table in List of Abbreviations is not wide enough. The data in this table does not look right anymore.
Can you please increase the table width?

**Comment by tobiasschweizer** [comment] 2018-10-26 13:00
duplicate of #47

**Closed as completed by tobiasschweizer** 2018-10-26 13:00 UTC
Labels: enhancement

**Comment by SepidehAlassi** [comment] 2018-10-26 13:01
oh I see!
